server:
  port: 18084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pm?serverTimezone=Asia/Shanghai
    #useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Abc123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
#mybatis-plus:
#  configuration:
#    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    type-handlers-package: com.example.test.mqtt
logging:
  path: /opt/iot/logs
  level:
    com:
      example:
        test:
          mapper: error
uploadPath: /home/hesuser/upload